apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/sangsangplus"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "http://gateway-service/login/oauth2/code/google"
  USER_SERVICE_URL: "http://user-service:8082"
  LOGGING_LEVEL_COM_EXAMPLE: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  SERVER_PORT: "8082"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/sangsangplus"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  LOGGING_LEVEL_COM_EXAMPLE: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
  JWT_SECRET: bXlfc2VjcmV0X2tleV9mb3JfandfYXV0aGVudGljYXRpb24=  # base64 encoded jwt secret
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: eW91ci1nb29nbGUtY2xpZW50LWlk  # placeholder Google OAuth2 client ID
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA==  # placeholder Google OAuth2 client secret
---
apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'